services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    links:
      - app
  app:
    build: app
    ports:
      - "8081:8081"
    environment:
      - FLASK_RUN_PORT=8081
      - FLASK_RUN_HOST=0.0.0.0
